# Generated by Django 4.0.6 on 2022-11-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_add_remove_employee_address_remove_employee_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
